export const Home = () => {
    return(<>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
        <div>
            <h1>prueba</h1>
        </div>
    </>

    )
}